[BitTorrent]
Session\DefaultSavePath=/data/torrents
Session\TempPathEnabled=false
Session\Interface=tun0
Session\InterfaceName=tun0
Session\QueueingSystemEnabled=false

[LegalNotice]
Accepted=true

[Preferences]
WebUI\Port=8080
WebUI\LocalHostAuth=false
WebUI\HostHeaderValidation=false
